Process Process-1:
Traceback (most recent call last):
  File "/global/cscratch1/sd/krisb/fireworks/fireworks_virtualenv/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/global/cscratch1/sd/krisb/fireworks/fireworks_virtualenv/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/global/u1/k/krisb/ase-3.15.0/lib/python2.7/site-packages/ase-3.15.0-py2.7.egg/ase/atoms.py", line 684, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/global/u1/k/krisb/ase-3.15.0/lib/python2.7/site-packages/ase-3.15.0-py2.7.egg/ase/calculators/vasp/vasp.py", line 229, in get_potential_energy
    self.update(atoms)
  File "/global/u1/k/krisb/ase-3.15.0/lib/python2.7/site-packages/ase-3.15.0-py2.7.egg/ase/calculators/vasp/vasp.py", line 83, in update
    self.calculate(atoms)
  File "/global/u1/k/krisb/ase-3.15.0/lib/python2.7/site-packages/ase-3.15.0-py2.7.egg/ase/calculators/vasp/vasp.py", line 106, in calculate
    self.run()
  File "/global/u1/k/krisb/ase-3.15.0/lib/python2.7/site-packages/ase-3.15.0-py2.7.egg/ase/calculators/vasp/vasp.py", line 168, in run
    exec(compile(open(vasp).read(), vasp, 'exec'), {}, locals)
IOError: [Errno 2] No such file or directory: './run_vasp.py'
